# Generated by Django 3.0.7 on 2021-03-28 18:14

import authapp.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('sticker', 'STICKER')], default='sticker', max_length=200)),
                ('location', models.CharField(choices=[('PH', 'Philippines')], default='PH', max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('mobile', phone_field.models.PhoneField(max_length=31)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('quantiy', models.PositiveIntegerField(default=0)),
                ('order_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('file', models.ImageField(blank=True, default='', upload_to='documents/%Y/%m/%d/', validators=[authapp.models.validate_image], verbose_name='Image')),
                ('total_price', models.DecimalField(blank=True, decimal_places=10, default=0.0, max_digits=20, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
