# Generated by Django 3.0.7 on 2021-03-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='mobile',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
