# Generated by Django 3.0.7 on 2021-04-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20210401_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='material',
            field=models.CharField(choices=[('sticker regular', 'STICKER REGULAR'), ('sticker die cut', 'STICKER DIE CUT'), ('transparent', 'TRANSPARENT'), ('transparent die cut', 'TRANSPARENT DIE CUT')], default='sticker regular', max_length=200),
        ),
    ]
