# Generated by Django 3.0.9 on 2021-03-25 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
