# Generated by Django 3.0.9 on 2021-03-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_ordermodel_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='file',
            field=models.FileField(default='', upload_to='documents/%Y/%m/%d/'),
        ),
    ]
