# Generated by Django 3.0.9 on 2021-03-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_auto_20210325_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
