# Generated by Django 3.0.9 on 2021-03-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_auto_20210325_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='height',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=1),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='quantiy',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=1),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='width',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=1),
        ),
    ]
