# Generated by Django 3.0.9 on 2021-03-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_auto_20210325_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='height',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='quantiy',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='width',
            field=models.IntegerField(default=1),
        ),
    ]
