# Generated by Django 3.0.9 on 2021-03-26 06:43

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_auto_20210325_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='country',
            field=django_countries.fields.CountryField(default='PH', max_length=2, multiple=True),
        ),
    ]
