# Generated by Django 3.0.9 on 2021-03-26 06:47

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0017_auto_20210326_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='mobile',
            field=phone_field.models.PhoneField(help_text='Contact phone number', max_length=31),
        ),
    ]
