"""
Django settings for src project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
from environ import Env
import os

# Environment Variables
env = Env()
env.read_env(env_file='src/.env')

BASEPATH = Path(__file__).resolve().parent.parent
TEMPLATE_DIR = os.path.join('templates', BASEPATH)

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT  = os.path.join(PROJECT_ROOT, 'staticfiles')
STATIC_URL = '/static/'


# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Old static setting
# BASEPATH = Path(__file__).resolve().parent.parent
# TEMPLATE_DIR = os.path.join('templates', BASEPATH)
# STATIC_DIR = os.path.join('static', BASEPATH)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = env('SECRET_KEY')

#Twilio
ACCOUNT_SECURITY_API_KEY = env('ACCOUNT_SECURITY_API_KEY')
TWILIO_ACCOUNT_SID = env('TWILIO_ACCOUNT_SID')
TWILIO_VERIFICATION_SID = env('TWILIO_VERIFICATION_SID')
TWILIO_AUTH_TOKEN = env('TWILIO_AUTH_TOKEN')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*',]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 'django-storages[google]',
    'storages',
    'widget_tweaks',
    'phone_field',
    'authapp',
    'bootstrap4',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'src.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR, ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'src.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# DB local settings
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': str(BASEPATH / 'db.sqlite3'),
#     }
# }


# For Google App ENGINE
import pymysql  # noqa: 402
pymysql.version_info = (1, 4, 6, 'final', 0)  # change mysqlclient version
pymysql.install_as_MySQLdb()


if os.getenv('GAE_APPLICATION', None):
    # Running on production App Engine, so connect to Google Cloud SQL using
    # the unix socket at /cloudsql/<your-cloudsql-connection string>
    DATABASES = {
        'default': {
            'ENGINE': env('ENGINE'),
            'HOST': env('HOST'),
            'USER': env('USER'),
            'PASSWORD': env('PASSWORD'),
            'NAME': env('NAME'),
        }
    }
else:
    # Running locally so connect to either a local MySQL instance or connect to
    # Cloud SQL via the proxy. To start the proxy via command line:
    #
    #     $ cloud_sql_proxy -instances=[INSTANCE_CONNECTION_NAME]=tcp:3306
    #
    # See https://cloud.google.com/sql/docs/mysql-connect-proxy
    DATABASES = {
        'default': {
            'ENGINE': env('ENGINE_LOC'),
            'HOST': env('HOST_LOC'),
            'PORT': env('PORT_LOC'),
            'NAME': env('NAME_LOC'),
            'USER': env('USER_LOC'),
            'PASSWORD': env('PASSWORD_LOC'),
        }
    }


# Local DB Sqlite3
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': str(BASEPATH / 'db.sqlite3'),
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

# Localhost setting
# Old static settings 2
# STATIC_URL = '/static/'
# STATICFILES_DIRS = [os.path.join(BASEPATH, 'static')]
# STATIC_ROOT = os.path.join(BASEPATH, 'staticfiles')

STATICFILES_DIRS = (
    os.path.join(PROJECT_ROOT, 'static'),
)


LOGIN_REDIRECT_URL = 'authapp:dashboard'
LOGIN_URL = 'login'
LOGOUT_URL = 'logout'

# Email Backend
EMAIL_BACKEND = env('EMAIL_BACKEND')
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_USE_TLS = env('EMAIL_USE_TLS')
EMAIL_PORT = env('EMAIL_PORT')
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')

# Images file
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(str(BASEPATH), 'media')

#Login url
LOGIN_URL = "/"

#Google Cloud storages

DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
GS_BUCKET_NAME = 'master-magnet-309002.appspot.com'
STATICFILES_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'

#Google credentials

os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="src/master-magnet-309002-08264ddb8fea.json"
